# Generated by Django 2.1.2 on 2019-01-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NuevaNot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=52)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=52)),
                ('link', models.URLField()),
            ],
        ),
    ]
