# Generated by Django 2.1.2 on 2019-01-25 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevanot',
            name='imagen',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
