# Generated by Django 2.1.2 on 2019-01-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC', '0002_nuevanot_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuevanot',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nuevanot',
            name='link',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='nuevanot',
            name='titulo',
            field=models.CharField(max_length=30),
        ),
    ]
