# Generated by Django 2.1.2 on 2019-02-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC', '0003_auto_20190130_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuevanot',
            name='imagen',
            field=models.FileField(upload_to=''),
        ),
    ]
