# Generated by Django 2.1.2 on 2019-02-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC', '0005_remove_nuevanot_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevanot',
            name='imagen',
            field=models.ImageField(default='bin.jpg', upload_to='media/img/'),
        ),
    ]
