# Generated by Django 2.1.2 on 2019-02-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC', '0006_nuevanot_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuevanot',
            name='imagen',
            field=models.ImageField(default='', upload_to='media/img/'),
        ),
    ]
