# Generated by Django 2.1.2 on 2019-02-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC', '0008_auto_20190221_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuevanot',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
    ]
