# Generated by Django 2.1.2 on 2019-02-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC', '0010_auto_20190221_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuevanot',
            name='link',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='nuevanot',
            name='titulo',
            field=models.CharField(max_length=500),
        ),
    ]
